name: Update Snake Animation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Snake Animation
        run: python snake.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "vaidikbhongade@gmail.com"
          git config --local user.name "Vaidik-Bhongade"
          git add README.md
          git commit -m "Updated Snake Animation" || echo "No changes to commit"
          git push
